[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "mlinphysics"
dynamic = ["version"]
description = "A module for the ML examples in the course Machine Learning in Physics at Florida State University."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Harrison B. Prosper", email = "hprosper@fsu.edu" }]
dependencies = [
    "drwho @ git+https://github.com/hbprosper/drwho.git@main",
    "h5py",
    "networkx",
    "sympy",
    "tqdm",
]

[project.optional-dependencies]
pyg = ["torch-geometric"]

[project.urls]
Homepage = "https://github.com/hbprosper/mlinphysics"

[tool.setuptools]
packages = ["mlinphysics", "mlinphysics.utils"]

[tool.setuptools.dynamic]
version = {attr = "mlinphysics.__version__"}
