name: TML
file:
  config: runs/TLM/TLM_config.yaml
  losses: runs/TLM/TLM_losses.csv
  params: runs/TLM/TLM_params.pth
  init_params: runs/TLM/TLM_init_params.pth
  plots: runs/TLM/TLM_plots.png
train_size: 12000
val_size: 156
test_size: 800
batch_size: 32
monitor_step: 100
delete: true
frac: 0.01
n_steps: 1
n_iterations: 400000
n_iters_per_step: 400000
base_lr: 0.0002
gamma: 0.5
DATAFILE: ../data/seq2seq_series_2terms.txt
MAX_SEQ_LEN: 128
EMB_DIM: 64
LAYERS: 3
HEADS: 8
FF_DIM: 128
DROPOUT: 0.1
VOCAB_SIZE: 40
PAD: 0
SOS: 1
EOS: 2
SEP: 3
